imports:
    - http://www.getcloudify.org/spec/cloudify/3.1/types.yaml

plugins:
    vcloud:
        executor: central_deployment_agent
        source: https://github.com/achirko/tosca-vcloud-plugin/archive/master.zip

node_types:
    cloudify.vcloud.nodes.Server:
        derived_from: cloudify.nodes.Compute
        properties:
            server:
                name:
                    default: ''
                catalog:
                    default: ''
                template:
                    default: ''
            vcloud_config:
                default: {}
        interfaces:
            cloudify.interfaces.lifecycle:
                create:
                    implementation: vcloud.server_plugin.server.create
                    inputs: {}
                start:
                    implementation: vcloud.server_plugin.server.start
                    inputs: {}
                stop:
                    implementation: vcloud.server_plugin.server.stop
                    inputs: {}
                delete:
                    implementation: vcloud.server_plugin.server.delete
                    inputs: {}
            cloudify.interfaces.host:
                get_state:
                    implementation: vcloud.server_plugin.server.get_state
                    inputs: {}

    cloudify.openstack.nodes.FloatingIP:
        derived_from: cloudify.nodes.VirtualIP
            properties:
                floatingip:
                default: {}
        use_external_resource:
            default: false
            resource_id:
                default: ''
            openstack_config:
                default: {}
        interfaces:
            cloudify.interfaces.lifecycle:
                create:
                    implementation: vcloud.network_plugin.floatingip.create
                    inputs: {}
                delete:
                    implementation: vcloud.network_plugin.floatingip.delete
                    inputs: {}
            cloudify.interfaces.validation:
                creation:
                    implementation: openstack.neutron_plugin.floatingip.creation_validation
                    inputs: {}
